### ISSUE TITLE
pwnable.kr/collision

### ISSUE THREAD

**Issue by velscode** [ZiyaoXie/Pwn#6]
Daddy told me about cool MD5 hash collision today.
I wanna do something like that too!

ssh col@pwnable.kr -p2222 (pw:guest)

**Comment by ziyaoxie** [comment]
Here's a solution in [pwnable.kr/collision/README.md](https://github.com/ZiyaoXie/Pwn/blob/main/pwnable.kr/collision/README.md) and #3.

Also a list of some [write-ups](https://github.com/ZiyaoXie/Pwn/blob/main/pwnable.kr/README.md) for pwnable.kr is available.

**Comment by velscode** [comment]
thx, this issue could close
